INSERT INTO item (item_name, item_price) VALUES ('Burger', 5.00);
INSERT INTO item (item_name, item_price) VALUES ('Nuggets', 3.25);
INSERT INTO item (item_name, item_price) VALUES ('9999999French fried', 2.50);
INSERT INTO item (item_name, item_price) VALUES ('Coffee', 1.55);
INSERT INTO item (item_name, item_price) VALUES ('Tea', 1.10);
INSERT INTO item (item_name, item_price) VALUES ('ChickenBurger', 3.50);
INSERT INTO item (item_name, item_price) VALUES ('GrillBurger', 4.00);
INSERT INTO item (item_name, item_price) VALUES ('DoubleTrouble Burger', 7.00);
INSERT INTO item (item_name, item_price) VALUES ('Cola 0,5', 1.50);
INSERT INTO item (item_name, item_price) VALUES ('Sprite 0,5', 1.50);
INSERT INTO item (item_name, item_price) VALUES ('Latte', 2.50);